version: '2'

services:
  db:
    image: mongo
    container_name: mongodb
    networks:
      - app-network
  app:
    container_name: nodeapp
    build:
      context: .
      dockerfile: AppNodeDockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge